# Generated by Django 6.0.2 on 2026-04-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createpost', '0002_alter_post_image_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
